swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  '/mspec/create':
    post:
      tags:
        - Create Message Definition
      summary: Create Message Definition
      operationId: createMessageDefinition
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: entity
          in: body
          description: MessageSpecification JSON object
          required: true
          schema:
            $ref: '#/definitions/MessageSpecification'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/mspec/get/{specId}':
    get:
      tags:
        - Get Message Definition
      summary: Retreive Message Definition
      operationId: getMessageDefinition
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Message Spec id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/MessageSpecification'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/mspec/delete':
    delete:
      tags:
        - Delete All Message Definitions
      summary: Delete All Message Definitions
      operationId: deleteAllMessageDefinitions
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/mspec/delete/{specId}':
    delete:
      tags:
        - Delete Message Definition
      summary: Delete Message Definition
      operationId: deleteMessageDefinition
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Message Spec id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/mspec/list':
    get:
      tags:
        - List Message Definitions
      summary: List Message Definition
      operationId: listMessageDefinitions
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: page
          in: query
          description: Page index, starts from 0
          required: false
          type: integer
          format: int32
        - name: pageSize
          in: query
          description: Maximum number of objects to be listed
          required: false
          type: integer
          format: int32
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: next
          in: query
          description: If next is true, **eid** is required
          required: false
          type: boolean
        - name: specId
          in: query
          description: Last Message Definition Id of the previous list operation, **required** if **next** is true
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/MessageSpecification'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/mspec/countall':
    get:
      tags:
        - Count All Message Definition
      summary: Count All Message Definition
      operationId: countAllMessageDefinitions
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in admin user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/mspec/count':
    get:
      tags:
        - Count Domain Message Definitions
      summary: Count Domain Message Definitions
      operationId: countDomainMessageDefinitions
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/mspec/create/field/{specId}':
    post:
      tags:
        - Create Message Field
      summary: Create Message Field
      operationId: createMessageField
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Message Spec id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: entity
          in: body
          description: MessageField JSON object
          required: true
          schema:
            $ref: '#/definitions/MessageField'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/MessageSpecification"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/mspec/modify/field/{specId}':
    post:
      tags:
        - Modify Message Field
      summary: Modify Message Field
      operationId: modifyMessageField
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Message Spec id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: entity
          in: body
          description: MessageField JSON object
          required: true
          schema:
            $ref: '#/definitions/MessageField'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/MessageSpecification"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/mspec/remove/field/{specId}/{name}':
    delete:
      tags:
        - Delete Message Field
      summary: Delete Message Field
      operationId: deleteMessageField
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Message Spec id
          required: true
          type: string
        - name: name
          in: path
          description: Field Name
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/mspec/count/fields/{specId}':
    get:
      tags:
        - Count Message Definition Fields
      summary: Count Message Definition Fields
      operationId: countMessgeDefinitionFields
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Message Spec id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in admin user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  Count:
    type: object
    required:
      - total
    properties:
      total:
        type: integer
        format: int64
  MessageField:
    type: object
    required:
      - name
      - dataType
    properties:
      domainKey:
        type: string
      specId:
        type: string
      name:
        type: string
      dataType:
        type: string
        enum:
         - BOOLEAN
         - BYTE
         - CHAR
         - SHORT
         - INT
         - LONG
         - FLOAT
         - DOUBLE
         - STRING
         - UUID
         - BLOB
         - JSON
      description:
        type: string
      indexed:
        type: boolean
      fulltextIndexed:
        type: boolean
  MessageSpecification:
    type: object
    required:
      - specId
      - name
      - fields
    properties:
      domainKey:
        type: string
      specId:
        type: string
      name:
        type: string
      description:
        type: string
      fields:
        type: array
        items:
          $ref: '#/definitions/MessageField'
      createdStamp:
        type: integer
        format: int64
      updatedStamp:
        type: integer
        format: int64
  Success: 
    type: "object"
    required:
      - code
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
